tsvwg/ietf-multipath-dccp

draft-ietf-tsvwg-multipath-dccp.mkd
update definition of path priorities
=> Re-definiton of MP_PRIO for fine granular steering of path priorities, backup and disabled paths

draft-ietf-tsvwg-multipath-dccp.mkd
worked on the operational section
=> Improve operational section

.cspell.json, draft-ietf-tsvwg-multipath-dccp.mkd
=> Define reordering and scheduling as out-of-scope 

draft-ietf-tsvwg-multipath-dccp.mkd
=> Enhance MP-DCCP concept section

draft-ietf-tsvwg-multipath-dccp.mkd
=> ECDHE description enhanced

draft-ietf-tsvwg-multipath-dccp.mkd
=> Remove temporal refernces

draft-ietf-tsvwg-multipath-dccp.mkd
added several clarification text passages for the prio part.
=> Extend MP_PRIO definition

draft-ietf-tsvwg-multipath-dccp.mkd
=> Improve MP_ADDADDR description

draft-ietf-tsvwg-multipath-dccp.mkd
=> Remove IP address and port from MP_REMOVEADDR HMAC calculation

draft-ietf-tsvwg-multipath-dccp.mkd
=> Define order of MP_HMAC and associated MP option

draft-ietf-tsvwg-multipath-dccp.mkd
=> Clarification HMAC belonging to MP_JOIN procedure triggers fallback

draft-ietf-tsvwg-multipath-dccp.mkd
=> Add recommendation for releasing Address ID

.cspell.json, draft-ietf-tsvwg-multipath-dccp.mkd
Resolves #131, resolves #132, resolves #133
Invalidates #130
=> Update MP_CONFIRM to use MP_SEQ

draft-ietf-tsvwg-multipath-dccp.mkd
=> Update references in Operation Overviews

draft-ietf-tsvwg-multipath-dccp.mkd
=> Optimize wording for MP_ADDADDR w/o specified port

draft-ietf-tsvwg-multipath-dccp.mkd
=> Change MP_PRIO to be path specific

draft-ietf-tsvwg-multipath-dccp.mkd
=> address UDP and non-TCP traffic suitability of MP-DCCP

draft-ietf-tsvwg-multipath-dccp.mkd
=> clarify policy for key type assignment

draft-ietf-tsvwg-multipath-dccp.mkd
=> version number entry detailed in IANA section

draft-ietf-tsvwg-multipath-dccp.mkd
=> added IANA considerations for future suboptions

draft-ietf-tsvwg-multipath-dccp.mkd
=> Implementation specific proposal to limit number of paths

draft-ietf-tsvwg-multipath-dccp.mkd
=> Notification of peer why path was discarded

draft-ietf-tsvwg-multipath-dccp.mkd
=> Informative guidance when not to send MP_ADDADDR

.cspell.json, draft-ietf-tsvwg-multipath-dccp.mkd
=> Define clearly MP_CONFIRM's "List of confirmations"

draft-ietf-tsvwg-multipath-dccp.mkd
Implemented changes to cope with Simones comment on CCID. Added Definition of what a CCID is in the operational section.
=> Introduce CCID Framework

draft-ietf-tsvwg-multipath-dccp.mkd
Edit of 'IANA considerations' section relating to issues #179 to #183.
=> Edit related to Issues #179 to #183 

.cspell.json, draft-ietf-tsvwg-multipath-dccp.mkd
First stab at adding MP_PRIO example to MP_CONFIRM section as well as adding a new section on "Address knowledge exchange" containing further examples.
Hopefully I have interpreted the descriptions of MP_CONFIRM.MP_PRIO/MP_ADDADDR and MP_REMOVEADDR correctly!
Closes #170
=> #170 nits and etc

draft-ietf-tsvwg-multipath-dccp.mkd
=> Add error handling for specific suboptions

draft-ietf-tsvwg-multipath-dccp.mkd
=> Example of concatenating MP options with multiple MP_HMACs

draft-ietf-tsvwg-multipath-dccp.mkd
Following the guidance of the chairs in https://mailarchive.ietf.org/arch/msg/tsvwg/R1arXySjvOOwVEoBC7CVQqC-5iU/
=> Update document status for MP-DCCP as PS

draft-ietf-tsvwg-multipath-dccp.mkd
=> Normative language and better reference for MP-DCCP closing principle

draft-ietf-tsvwg-multipath-dccp.mkd
following Med's suggestion on the mailinglist:
https://mailarchive.ietf.org/arch/msg/tsvwg/oJg2ErIj582FUePRtZfJyqVPPoE/
=> Strength coupled congestion control statement

draft-ietf-tsvwg-multipath-dccp.mkd
=> Improved Maximum Packet Size text

draft-ietf-tsvwg-multipath-dccp.mkd
=> Declare appendix as Informative

draft-ietf-tsvwg-multipath-dccp.mkd
=> Replace feature number 10 with THIS-FEATURE

draft-ietf-tsvwg-multipath-dccp.mkd
=> Clarify soft-state in MP_ADDADDR

draft-ietf-tsvwg-multipath-dccp.mkd
=> DCCP-Reset MUST follow an unknown MP_JOIN token

draft-ietf-tsvwg-multipath-dccp.mkd
=> MP_REMOVEADDR closing procedure improved

draft-ietf-tsvwg-multipath-dccp.mkd
=> Improved text on MP_PRIO=0 handling

draft-ietf-tsvwg-multipath-dccp.mkd
=> MP_SEQ use for MP_PRIO: Improved reference

draft-ietf-tsvwg-multipath-dccp.mkd
=> Improved MP_EXP text related to private use

draft-ietf-tsvwg-multipath-dccp.mkd
=> MP_EXP length/type clarification

draft-ietf-tsvwg-multipath-dccp.mkd
This contains a review of the language and the standards terms to try to imporve readability. Please accept or modify as needed.
=> Request to tidy the language in MP-DCCP

draft-ietf-tsvwg-multipath-dccp.mkd
=> MP_ADDADDR text updated

draft-ietf-tsvwg-multipath-dccp.mkd
closes #234. some additional minor language changes in the text suggested.
=> Abstract text updated

draft-ietf-tsvwg-multipath-dccp.mkd
=> Better text to explain that version 0 is specified

draft-ietf-tsvwg-multipath-dccp.mkd
=> ECDHE key usage example with separate certificate usage

draft-ietf-tsvwg-multipath-dccp.mkd
=> Within MP_CONFIRMATION description specify "dataset"

.cspell.json, draft-ietf-tsvwg-multipath-dccp.mkd
Added comparison to MP-QUIC in the introduction
=> Add MP-QUIC comparison to introduction section

draft-ietf-tsvwg-multipath-dccp.mkd
=> Improve the description of MP_CAPABLE and its negotiation

draft-ietf-tsvwg-multipath-dccp.mkd
=> Specify the order of confirmed suboptions within MP_CONFIRM

draft-ietf-tsvwg-multipath-dccp.mkd
=> Security consideration for MPS

draft-ietf-tsvwg-multipath-dccp.mkd
=> Add "Maximum SubFlows Consideration" section

draft-ietf-tsvwg-multipath-dccp.mkd
=> Add reference to the security implications of MP-DCCP-capable middleboxes

draft-ietf-tsvwg-multipath-dccp.mkd
Solves issue #246 and corrects missing braces
=> Add information abour MP_RTT type and correct missing braces

.cspell.json, draft-ietf-tsvwg-multipath-dccp.mkd
=> Add further names to Acknowledgments section

draft-ietf-tsvwg-multipath-dccp.mkd
This is a partial response to issue #233 that covers the extended overview.
closes #237
=> Overview in Section 2 expanded

.cspell.json, draft-ietf-tsvwg-multipath-dccp.mkd
Covers the second part of issue #233 .
=> Add state diagram

draft-ietf-tsvwg-multipath-dccp.mkd
=> Improve IANA Key Type registry request

draft-ietf-tsvwg-multipath-dccp.mkd
=> Added missing entry to MP_OPT overview table

draft-ietf-tsvwg-multipath-dccp.mkd
=> Rename Feature name for MP Capable for IANA registration

draft-ietf-tsvwg-multipath-dccp.mkd
=> Amendments due to the review during the WGLC

draft-ietf-tsvwg-multipath-dccp.mkd
=> Adoption of Med's editorial suggestions

draft-ietf-tsvwg-multipath-dccp.mkd
=> Remove expired references to IETF draft documents

draft-ietf-tsvwg-multipath-dccp.mkd
=> Remove comparison with MP-QUIC

draft-ietf-tsvwg-multipath-dccp.mkd
=> Changed order of Subflow and Connection in Terminology section

draft-ietf-tsvwg-multipath-dccp.mkd
=> Explained physically isolated paths

draft-ietf-tsvwg-multipath-dccp.mkd
=> Path scope refined

draft-ietf-tsvwg-multipath-dccp.mkd
=> Added enhanced Maximum number of Subflows Considerations

draft-ietf-tsvwg-multipath-dccp.mkd
=> Elimination of level confusion

draft-ietf-tsvwg-multipath-dccp.mkd
=> Improved introduction of the maximum number of subflows section

draft-ietf-tsvwg-multipath-dccp.mkd
=> Improved justification for 48-bit sequence number space

draft-ietf-tsvwg-multipath-dccp.mkd
=> Changed the confirmation of MP_PRIO to MUST

draft-ietf-tsvwg-multipath-dccp.mkd
=> Prevention of replay attacks on MP_ADDADDR and REMOVEADDR

draft-ietf-tsvwg-multipath-dccp.mkd
Note: In some places MP_PRIO is talked about as an option, and at other points a sub option. It's good to be consistent, but this does not change the spec!
=> Suggest updates to MP_PRIO

draft-ietf-tsvwg-multipath-dccp.mkd
=> Link Path definition with MPTCP RFC8684

draft-ietf-tsvwg-multipath-dccp.mkd
Attempt to align requirements/objectives
=> Align requirements/objectives in Security Considerations section

draft-ietf-tsvwg-multipath-dccp.mkd
=> Mandatory Key Type 0 support in implementation

draft-ietf-tsvwg-multipath-dccp.mkd
=> ARTreview Telechat nits

draft-ietf-tsvwg-multipath-dccp.mkd
=> Nits from the Internet AD review fixed

draft-ietf-tsvwg-multipath-dccp.mkd
=> Comments from the RTG AD review fixed

draft-ietf-tsvwg-multipath-dccp.mkd
=> Comments from the 2nd INT AD review fixed

draft-ietf-tsvwg-multipath-dccp.mkd
=> Add RFC Required policy for IANA considerations

draft-ietf-tsvwg-multipath-dccp.mkd
=> Address Mahesh's AD review

draft-ietf-tsvwg-multipath-dccp.mkd
=> Address Deb's COMMENT

draft-ietf-tsvwg-multipath-dccp.mkd
=> Murray's DISCUSS comments

draft-ietf-tsvwg-multipath-dccp.mkd
=> Improved/replaced SHOULD NOT usage
