draft-ietf-tsvwg-multipath-dccp.mkd
close #49 . No encoding is necessary, as the text states that the options to be confirmed must be copied verbatim.
=> Remove Tbd : MP_CONFIRM encoding list of options

draft-ietf-tsvwg-multipath-dccp.mkd
no need to be redundant, but focus only on the new codepoints. 
The IANA registry is authoritative here.
=> Edits to Section "3.  MP-DCCP Protocol"

draft-ietf-tsvwg-multipath-dccp.mkd
to address nits mentioned by Simone in issues 161/162 - quotation "sub-flow" resembles wording used in RFC4340 (issue 163)
=> adapted wording in abstract/intro

.cspell.json, draft-ietf-tsvwg-multipath-dccp.mkd
```
====
In section 2, I saw:
The number of concurrent DCCP subflows can vary during the lifetime
of a Multipath DCCP connection.  The details of the path management
decisions for when to add or remove subflows are outside the scope of
this document.
I’d suggest:
The number of MP-DCCP subflows can vary during the lifetime
of a Multipath DCCP connection.  The details of the path management
decisions for when to add or remove subflows are outside the scope of
this document.
or /active subflows/ if that somehow makes sense, but not concurrent!
====
I’d be happy to see the reference to RFC3124 and discussion of CM 
disappear, since this was not a great story. However, I would not resist 
if you insist on keeping this.
===
Alas you really ought not to mention or reference RFC5634, that also …
```
=> Gorry's early review

draft-ietf-tsvwg-multipath-dccp.mkd
Text was already shifted to "Path usage strategies" section
Closes #208
=> Removed EXP related text from CC sonsiderations

draft-ietf-tsvwg-multipath-dccp.mkd
Text updated. Host A and host B description included to clairfy the steps. Action in the case of a missing response from host B clarified - retransmission suggested.
DCCP timeout is left to be clarified - MP-TCP has RTO and the concept of retransmission - what is the equivalent in DCCP?
=> #243 MP_FAST_CLOSE

draft-ietf-tsvwg-multipath-dccp.mkd
=> Rename MP-DCCP Suboption to Multipath Suboption

draft-ietf-tsvwg-multipath-dccp.mkd
```
It would help readers not already familiar with DCCP to provide or point to a
small summary of its basic mechanics. In particular, a description of how it
achieves what it intends in the presence of loss, and pointing out that
"retransmit" means "send again with a new sequence number" would help readers
with this document.
```
=> Pointer to used DCCP basics

draft-ietf-tsvwg-multipath-dccp.mkd
```
Why is the fragment ", which means that the client and server must support it"
present at the end of last sentence on page 10? I think the fragment can just
be deleted.
```
=> Removed unecessary description about version 0 support

draft-ietf-tsvwg-multipath-dccp.mkd
```
In 3.2.10 you say "priority flag" exactly once. Suggest s/priority
flag/priority value/.
```
=> s/priority flag/priority value/

draft-ietf-tsvwg-multipath-dccp.mkd
```
At the first paragraph on page 11, SHOULD A or MUST B is an unclear
construction. I think you mean "MUST either A (which is preferred) or B".
```
=> Resolved unclear SHOULD MUST construction

draft-ietf-tsvwg-multipath-dccp.mkd
```
The discussion of requirements on "random" things, such as the nonces would
benefit from more precision. Bare pointers to 4086 aren't helpful. Discuss
why the IDNS should be set randomly.
```
=> Explain randomness of IDSN

draft-ietf-tsvwg-multipath-dccp.mkd
```
At the definition of Connection Identifier, "locally unique" is not a
sufficient description of what's required of the identifier.
```
=> "Locally unqiue" CI better explained

draft-ietf-tsvwg-multipath-dccp.mkd
```
Consider discussion what to do if a peer signals use of special addresses
(broadcast for example) in MP_ADDADDR.
```
=> Added discussion about advertising for non-unicast IP addresses

draft-ietf-tsvwg-multipath-dccp.mkd
```
The first sentence on page 4 (staring "The discovery and setup") does not parse.
Is "needs to be avoided" in the last sentence of that paragraph masking a
normative requirement?
```
=> Better formulation of the details of path management

draft-ietf-tsvwg-multipath-dccp.mkd
```
At the first paragraph of section 3, the document claims it is updating section
6.4 of RFC4340. I don't believe this document is doing such a thing. It is,
rather, adding an entry to an IANA registry, and the prose should say that
instead.
```
=> Clarification that new MP feature extends DCCP feature list

draft-ietf-tsvwg-multipath-dccp.mkd
```
Section 3.1 second paragraph, third sentence: This is a long run-on that does
not parse, please rework it as two or more sentences.
```
=> Split sentence describing MP feature value filed for better readability

draft-ietf-tsvwg-multipath-dccp.mkd
`Page 13: "confirmation of options is identified outdated" fails to parse.`
=> Improved language when describing the confirmation of obsolete options

draft-ietf-tsvwg-multipath-dccp.mkd
```
The document uses "tear down the connection" informally. Please consider
removing all such language and say instead what that means (in most instances
it's already been said).
```
=> Normative language in MP_FAST_CLOSE procedure

draft-ietf-tsvwg-multipath-dccp.mkd
```
At the first paragraph on page 18. "The CI is a unique number that is
configured per host" is imprecise and misleading. Avoid the word configured,
and spell out the uniqueness requirements for CI carefully here.
```
=> Uniqueness of CI emphasized in MP_KEY

draft-ietf-tsvwg-multipath-dccp.mkd
```
The exception in the last sentence of 3.2.6 is not clear. Consider a
restructure where you can make it clear what you are supposed to do with an
MP_HMAC that cannot be associated with a suboption when it is in a DCCP-Ack
in response to a DCCP-Response packet containing an MP_JOIN option at this
point in the text.
```
=> Better description of the MP_HMAC exception to be ignored

draft-ietf-tsvwg-multipath-dccp.mkd
```
Consider moving the last paragraph of 3.2.9 close to the very beginning of the
section.
```
=> Recommend to use MP_REMOVEADDR only in case of invalid IP

draft-ietf-tsvwg-multipath-dccp.mkd
```
At 3.2.10, the use of a capitalized SHOULD is not appropriate. It would be
better to say "The path priorities signaled with the MP_PRIO option are hints".
```
=> MP_PRIO removed unecessary SHOULD

draft-ietf-tsvwg-multipath-dccp.mkd
```
It's potentially misleading to mix normative statements and examples. The prose
on page 33 says the following options MUST be included, but then put example
values into the options.
```
=> Resolve mixture of normative statements and examples

draft-ietf-tsvwg-multipath-dccp.mkd
=> Incorrectly mentioned CI instead of derived key corrected

draft-ietf-tsvwg-multipath-dccp.mkd
```
Section 3.2.4: I find the notation confusing: hostA d-key(A)=(key-a+key-b).
Further, the use of "-" as part of the variable name is easy to confuse
with a math operator.  I suggest that the paragraph be reworded to show
how to compute key_d_a and key_d_b, which also avoids the key names
looking like functions.  Maybe:
Key Material is exchanged in plain text between hosts, and the key
parts (key_a, key_b) are used to generate the derived key (key_d)
by concatenating the two parts with the local key in front.
That is, key_d_a=key_a+key_b, and key_d_b=key_b+key_a.
If you accept this comment, then you might define the following:
*  HMAC(A) = …
```
=> Consistent and simplified naming of Key related variables

draft-ietf-tsvwg-multipath-dccp.mkd
```
Section 3.2.4: Is one of the Key Type mandatory-to-implement?  I realize
that does not make that Key Type mandatory-to-use.
```
=> No mandatory Key Type better explained

draft-ietf-tsvwg-multipath-dccp.mkd
```
Section 3.2.6: The text says:
...  In the event that an
MP_HMAC cannot be associated with a suboption, unless it is an
MP_HMAC sent in DCCP-Ack in response to a DCCP-Response packet
containing an MP_JOIN option, this MP_HMAC MUST be ignored.
This text begs for an explanation of MP_HMAC sent in DCCP-Ack in
response to a DCCP-Response packet containing an MP_JOIN option.
If a sentence will not cover it, then please add a pointer to the
part of the document that discusses this situation.
```
=> Clarified why DCCP-Ack may not carry an MP suboption

draft-ietf-tsvwg-multipath-dccp.mkd
```
Section 3.6: The text says: " (if this is not possible it MUST be
closed)."  Please reword.  Please do not burry the MUST statement in
a parenthetical.
```
=> The parenthesis around the MUST statement has been removed.

draft-ietf-tsvwg-multipath-dccp.mkd
```
Section 4: Please add a paragraph that describes the consequences for
choosing the Plain Text Key Type over ECDHE-C25519-SHA256 or
ECDHE-C25519-SHA512.
```
=> Adding the consequences of selecting a Key Type in terms of security

draft-ietf-tsvwg-multipath-dccp.mkd
```
Section 3.1: The text says:
Unlike the example in Figure 4, this document only allows the
negotiation of MP-DCCP version 0, which means that client and server
must support it.
I think it would be more clear to say:
Unlike the example in Figure 4, this document only allows the
negotiation of MP-DCCP version 0.  Therefore, successful
negotiation of MP-DCCP as defined in this document, the client
and the server MUST both support MP-DCCP version 0.
```
=> Better explanation of MPDCCP version 0 support

draft-ietf-tsvwg-multipath-dccp.mkd
```
Section 3.2.8:  The text says:
...  Note that an
implementation MAY discard incoming address advertisements - for
example, to avoid the required mapping state, or because advertised
addresses are of no use to it (for example, IPv6 addresses when it
has IPv4 only).  Therefore, a host MUST treat address advertisements
as soft state, and the sender MAY choose to refresh advertisements
periodically.
The nesting of examples makes this paragraph very difficult.  First,
please separate the MUST statement and the MAY statement.  Then, offer
examples to explain the reasons an implementation might choose to
discard incoming address advertisements or refresh …
```
=> Improved description of when address advertisements are useful or not

draft-ietf-tsvwg-multipath-dccp.mkd
```
General: Some sections use "Host A" and others use "host A".  Please
pick one capitalization convention and use it throughout the document.
```
=> All Host A/B capitalised for consitency

draft-ietf-tsvwg-multipath-dccp.mkd
```
General: Please use "bytes" (not "Bytes") when discussing the length of
a field or message.
General: Please use "bytes" or "octets" when discussing the length of
a field or message. I have a mild preference for octets, but consistency
is desired.
```
=> Consistent use of bytes in lower case

draft-ietf-tsvwg-multipath-dccp.mkd
`Section 1.2: Please consider adding a definition of 4-tuple.`
=> added a 4-tuple exampe for IPv4 and IPv6
